### ISSUE TITLE
Combine View with Day Partitioned Table

### ISSUE THREAD

**Issue by Madhu1512** [aws-samples/amazon-cloudfront-access-logs-queries#10]
Currently, I am doing Day Partitioned Table where anything older than a day will insert into it. Now I would like to combine the view with Day Partitioned Table.

Here is what I am doing.

SELECT *, \"$path\" as file FROM ${database}.${partitioned_gz_table} WHERE (concat(year, month, day, hour) >= date_format(date_trunc('hour', ((current_timestamp - INTERVAL  '15' MINUTE) - INTERVAL  '1' HOUR)), '%Y%m%d%H')) UNION ALL SELECT *, \"$path\" as file FROM ${database}.${partitioned_parquet_table} WHERE (concat(year, month, day, hour) < date_format(date_trunc('hour', ((current_timestamp - INTERVAL  '15' MINUTE) - INTERVAL  '1' HOUR)), '%Y%m%d%H')) UNION ALL SELECT *, \"$path\" as file FROM ${database}.${day_partitioned_parquet_table} WHERE (concat(year, month, day) < date_format(date_trunc('day', ((current_timestamp - INTERVAL  '15' MINUTE) - INTERVAL  '1' DAY), '%Y%m%d))

I am not sure if my query is right for what I am trying to achieve. What is the best way to achieve this?

**Comment by steffeng** [comment]
Hi @Madhu1512, yes, you can try this in the Amazon Athena console and check the results. 2 remarks:
- You should limit the 2nd union with a lower bound in the WHERE clause so it does not overlap with the 3rd one and return duplicates.
- The 15min have been picked as I expect the hourly partition transformation to finish within 15min. Maybe your daily transformation takes a longer amount of time.
