### ISSUE TITLE
Lambda Function moveAccessLogs.js Throwing Error - Logs aren't in Expected Format

### ISSUE THREAD

**Issue by Tessando** [aws-samples/amazon-cloudfront-access-logs-queries#11]
I set this up by launching the Stack as described. 

When I look at the S3 buckets, comparing the Old CloudFront log files to the New CloudFront log files they look the same. What I mean by "look the same" is that they both are in the format: distribution-ID.YYYY-MM-DD-HH.unique-ID.gz

But when I look at the log streams going into CloudWatch I see this format:
2020/10/12/7063690b6a7f417293f736568409fc3e

In Lambda I noticed that "MoveNewAccessLogsFn" is not working. Below is an error I get when I attempt to test:

START RequestId: c16a8df6-2390-4533-aeb9-53e364cf3b1a Version: $LATEST
2020-10-12T22:00:20.488Z	c16a8df6-2390-4533-aeb9-53e364cf3b1a	ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read property 'map' of undefined","stack":["TypeError: Cannot read property 'map' of undefined","    at Runtime.exports.handler (/var/task/moveAccessLogs.js:18:31)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: c16a8df6-2390-4533-aeb9-53e364cf3b1a
REPORT RequestId: c16a8df6-2390-4533-aeb9-53e364cf3b1a	Duration: 39.03 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 83 MB	Init Duration: 618.96 ms

Am I missing some permissions somewhere? How come I'm not seeing the log files in a year-month-day in S3?

Thanks in advance for your help.

**Comment by steffeng** [comment]
Hi Tessando, the AWS Lambda function is triggered by the event from Amazon S3 when a new file is put with the `/new` prefix. You can see this in the [code line from the error](https://github.com/aws-samples/amazon-cloudfront-access-logs-queries/blob/mainline/functions/moveAccessLogs.js#L18). For your test, you need to either put a log file as Amazon CloudFront would do or resemble the event structure in your test.

**Comment by Tessando** [comment]
Thank you for your fast response. I will attempt that change now.
