### ISSUE TITLE
Using Management Console to Place Log Files Under Root Bucket Assist

### ISSUE THREAD

**Issue by Tessando** [aws-samples/amazon-cloudfront-access-logs-queries#12]
I have multiple CloudFront distributions that I would like to use this for and would like to avoid having many Root S3 Buckets. 

Is is possible to change a parameter so that all CloudFront logs went to a given bucket, like for example a root bucket named "cf-logs". Is it possible to make this change using the Management Console so that "cf-logs" is the root bucket and "myapp1" is a folder inside that bucket? For example:

/cf-logs/myapp1

I attempted to make this change by manipulating the template.yaml file on the following lines:

	6 Instances of:
	arn:${AWS::Partition}:s3:::${ResourcePrefix}-${AWS::AccountId}-cf-access-logs

	2 instances of:
	s3://${ResourcePrefix}-${AWS::AccountId}-cf-access-logs/athena-query-results

	and 1 instance of:
	BucketName: !Sub "${ResourcePrefix}-${AWS::AccountId}-cf-access-logs"

But unfortunately I'm getting errors when I make these changes. 

Is there a way to do this using the Management Console so that I can have the log files go underneath a root bucket? 

Thank you for your assistance. This repo is really great and does exactly what I need it to!

**Comment by steffeng** [comment]
Hi Thom, thanks. Yes, unfortunately, it is not possible to import an existing Amazon S3 bucket in this (serverless) template. Is the use case the same as in issue #8? How many distributions do you have, 10/100/10000s...?

**Comment by Tessando** [comment]
I have 15 CloudFront distributions. 

Thanks for the fast response.
