### ISSUE TITLE
Suppressing the "Partitioned_Parquet" Table in CloudFormation 

### ISSUE THREAD

**Issue by Tessando** [aws-samples/amazon-cloudfront-access-logs-queries#13]
Is it possible to set this up to suppress the "partitioned_parquet" table at launch? I don't believe that I will be querying that table as what I need is in the "partitioned_gz" table.

Thank you for your help.

**Comment by steffeng** [comment]
Hi Thom, I'm afraid there is no pre-canned template for this. But you can [deploy a modified template](https://github.com/aws-samples/amazon-cloudfront-access-logs-queries#q-how-can-i-customize-and-deploy-the-template) yourself without the resources that compresses your data to parquet.

**Comment by Tessando** [comment]
Thank you for your help. I found four references that look like they build and create the Parquet Table. Can you please confirm that commenting these out will build this without Parquet being created?

- Line Numbers: 35-41 _Starting with_ ParquetKeyPrefix:
- Line Number: 83 TARGET_TABLE: !Ref PartitionedParquetTable
- Line Numbers: 278-369 _Starting with_ PartitionedParquetTable:
- Line Number: 84 _Starting with_ partitioned_parquet_table: !Ref PartitionedParquetTable - For this one I made sure to close the curly bracket.

One other question: Can I leave in the references to ".${partitioned_parquet_table}" in the "- - '/* Presto View: '" section? Or will the lack of that table being present cause an error?

Thanks again for your help and pointing me in the right direction.

**Comment by steffeng** [comment]
I'm afraid that is difficult to debug/ develop in a ticket conversation. But OTOH it's easy to try. Please delete/ deploy in iterations. It looks like kicking all resources out but `CfLogsDatabase`, `PartitionedGzTable`, `CloudFrontAccessLogsBucket`, `MoveNewAccessLogsFn`, and `CreatePartFn` could do the trick.
