### ISSUE TITLE
S3 bucket does not conform to AWS Foundational Security Best Practices

### ISSUE THREAD

**Issue by MaksimAniskov** [aws-samples/amazon-cloudfront-access-logs-queries#14]
The access logs bucket does not pass these checks:
[[S3.4] S3 buckets should have server-side encryption enabled](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-4) 
[[S3.5] S3 buckets should require requests to use Secure Socket Layer](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-5)

**Comment by steffeng** [comment]
Thanks @MaksimAniskov for your contribution!
