### ISSUE TITLE
Multiple Amazon CloudFront distributions pointing to the same bucket

### ISSUE THREAD

**Issue by yemartin** [aws-samples/amazon-cloudfront-access-logs-queries#23]
Hi @steffeng ! And first, thanks a lot for this. I have had my eyes on deploying this for a while, I am glad to finally have the opportunity!

I have yet another question about using this for multiple distributions (FYI we have about 15 now, going to have about 30).

I checked #8 and #12, but this is different: I don't care about partitioning the data by distribution (like in #8), or group the entire S3 data structure under subfolders (like in #12).

According the the FAQ:

> Q: How can I use the sample application for multiple Amazon CloudFront distributions?
> 
> Deploy another AWS CloudFormation stack

What about pointing multiple CF distributions to the same bucket's `new/`? Skimming the code, I did not see any obvious reason why it would be an issue, but the FAQ answer above makes it sound like the only way is to deploy another stack...

What am I missing? Will it work, or will it break something?

**Comment by steffeng** [comment]
Hi @yemartin. Sorry for the late response. Indeed, that should work as long as the volume of logs can still be processed within 15 minutes and you don't need the partitions to run the queries. Can you please share your experience so I can evolve the FAQ here?

**Comment by yemartin** [comment]
Hi @steffeng, and great timing: after testing it in staging for a while, we just started using this multi-distributions setup in production yesterday!

We are currently pointing five of our CloudFront distributions to the same `new/`, and it is working like a charm.

About performance: we have some moderate traffic, with sustained peaks at 30 requests per second. And the lambda functions are performing well: `TransformPartFn` completes in about 5 seconds, while `CreatePartFn` and `MoveNewAccessLogsFn` run in under 2 seconds. So we have a very comfortable margin to 15 minutes.

If we need logs of a single distribution, we filter by `host`. With only 24 hours of data, it is too early to tell if _not_ having per-distribution partitions will be an issue or not.

I am not sure what else to tell you. Is there anything else you would like to know about our experience?

**Comment by steffeng** [comment]
Thanks @yemartin for your feedback and the idea in the first place. I added it to the FAQ in the README.
