### ISSUE TITLE
Philly 10k cloudfront

### ISSUE THREAD

**Issue by twooutt11** [aws-samples/amazon-cloudfront-access-logs-queries#28]
Hello everyone,

I am new to github and I need some assistance. My personal information and identity is severely compromised. I would appreciate it if anyone can offer there input on how I can go about gaining control over my my personal info, and identity.

**Comment by steffeng** [comment]
@twooutt11, can you describe the issue further? What data got compromised? How is it related to this repository? If this is related to GitHub, reach out to support.github.com.

**Comment by twooutt11** [comment]
hey Steffeng thanks for the reply. Honestly Im not much of a programmer or developer. I have limited IT experience. I honestly have been thrown for a loop once i lost all my social media, and my main email and i cloud. This was 2 years ago and its been getting exponentially worse. any input or help or feedback would be greatly appreciated.

**Comment by twooutt11** [comment]
also my amazon got hacked and its called philly 10k cloudfront. its like a whole group that owns my icloud. they are making a show of it

**Comment by steffeng** [comment]
I'm afraid I can't help you with that since it's unrelated to this repository and will close the issue. Reach out to the companies' support functions, e.g. https://support.github.com and https://www.amazon.com/contact-us/. Good luck!
