### ISSUE TITLE
support hostheader as a partition to allow multiple sites to be handled by 1 bucket/stack

### ISSUE THREAD

**Issue by leecookson** [aws-samples/amazon-cloudfront-access-logs-queries#8]
Since the host header isn't in the log file name, it would need to be part of the log bucket's prefix configured in CloudFront to keep the lambda stateless when converting new log objects to the partition format.

We have lots of sites, and would like to avoid the overhead of setting up a new stack for each one, and also have the flexibility to query multiple sites at once while still maintaining the cost/performance benefits of using partitions.

**Comment by steffeng** [comment]
How many hostnames do you have, 10/100/10000s...? How many Amazon CloudFront distributions do you have?
Querying for the x-host-header in the logs does not do the trick?
